#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 011: Complete Domino Pip Detection

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: 011 - Complete Domino Pip Detection"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing cv-service dependencies..."
cd cv-service
if [ ! -d "venv" ]; then
    python -m venv venv
fi
source venv/bin/activate 2>/dev/null || . venv/Scripts/activate
pip install -q -r requirements.txt
cd ..

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting cv-service..."
cd cv-service
source venv/bin/activate 2>/dev/null || . venv/Scripts/activate
uvicorn main:app --reload --host 0.0.0.0 --port 8080 > ../cv-service.log 2>&1 &
CV_SERVICE_PID=$!
cd ..

wait_for_service 8080 "cv-service"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  cv-service:  http://localhost:8080"
echo "  API docs:    http://localhost:8080/docs"
echo ""
echo "Logs:"
echo "  cv-service:  tail -f cv-service.log"
echo ""
echo "PIDs:"
echo "  cv-service:  $CV_SERVICE_PID"
echo ""
echo "To stop all services:"
echo "  kill $CV_SERVICE_PID"
echo ""
echo "========================================"
echo "Ready for implementation!"
echo "========================================"
