#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 001
# Feature: Enhance AI Visual Pips Board Extraction Accuracy

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 001: AI Pips Extraction Accuracy"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/../../.." && pwd )"

echo "Project root: $PROJECT_ROOT"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready on port $port${NC}"
}

# Check for required environment variables
check_env_vars() {
    echo ""
    echo "Checking environment variables..."

    local missing=0

    if [ -z "$OPENROUTER_API_KEY" ]; then
        echo -e "${YELLOW}Warning: OPENROUTER_API_KEY not set${NC}"
        missing=$((missing + 1))
    fi

    if [ $missing -gt 0 ]; then
        echo -e "${YELLOW}Some API keys may be missing. Extraction may fail.${NC}"
    else
        echo -e "${GREEN}All required environment variables set${NC}"
    fi
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "========================================"
echo "Starting Services"
echo "========================================"

# 1. Start CV Service (Python FastAPI on port 8080)
echo ""
echo "Starting CV Service..."
cd "$PROJECT_ROOT/cv-service"

# Check if Python virtual environment exists
if [ -d ".venv" ]; then
    source .venv/bin/activate
elif [ -d "venv" ]; then
    source venv/bin/activate
fi

# Install dependencies if requirements.txt exists and not already installed
if [ -f "requirements.txt" ]; then
    pip install -q -r requirements.txt 2>/dev/null || true
fi

# Start CV service in background
uvicorn main:app --host 0.0.0.0 --port 8080 --reload &
CV_PID=$!
echo "CV Service PID: $CV_PID"

# 2. Start Expo Frontend (on port 8081/19000)
echo ""
echo "Starting Expo Frontend..."
cd "$PROJECT_ROOT/pips-solver"

# Install npm dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing npm dependencies..."
    npm install
fi

# Start Expo in background
npm run start &
EXPO_PID=$!
echo "Expo PID: $EXPO_PID"

# ============================================
# WAIT FOR SERVICES
# ============================================

echo ""
echo "========================================"
echo "Waiting for Services to Start"
echo "========================================"

wait_for_service 8080 "CV Service"
# Note: Expo dev server may take longer to start
sleep 5

# ============================================
# ENVIRONMENT CHECK
# ============================================

check_env_vars

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  CV Service:  http://localhost:8080"
echo "  CV Docs:     http://localhost:8080/docs"
echo "  Expo Metro:  http://localhost:8081"
echo "  Expo Dev:    http://localhost:19000"
echo ""
echo "Process IDs:"
echo "  CV Service:  $CV_PID"
echo "  Expo:        $EXPO_PID"
echo ""
echo "To stop services:"
echo "  kill $CV_PID $EXPO_PID"
echo ""
echo "========================================"
echo "Ready to implement Spec 001"
echo "========================================"
