#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 012

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 012: Improved Region Detection"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing cv-service dependencies..."
cd cv-service
pip install -r requirements.txt
cd ..

# Ensure scikit-learn is installed for DBSCAN/MeanShift
echo "Ensuring scikit-learn is available..."
pip install scikit-learn scipy

echo ""
echo -e "${GREEN}Dependencies installed${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting cv-service..."
cd cv-service
uvicorn main:app --reload --port 8080 &
cd ..

wait_for_service 8080 "cv-service"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  cv-service: http://localhost:8080"
echo "  cv-service docs: http://localhost:8080/docs"
echo ""
echo "Test commands:"
echo "  pytest cv-service/test_e2e_extraction.py -v"
echo ""
echo "To stop services:"
echo "  pkill -f 'uvicorn main:app'"
echo ""
