#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 016: Diamond Cell Inference Completion

set -e

echo "========================================"
echo "Diamond Cell Inference - Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# ENVIRONMENT SETUP
# ============================================

echo ""
echo "[1/3] Checking Python environment..."

# Check Python version
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python not found. Please install Python 3.8+${NC}"
    exit 1
fi

PYTHON_VERSION=$(python --version 2>&1 | awk '{print $2}')
echo -e "${GREEN}Python $PYTHON_VERSION found${NC}"

# Check if in pips-agent directory
if [ ! -f "pips-agent/main.py" ]; then
    echo -e "${YELLOW}Warning: pips-agent/main.py not found. Make sure you're in project root.${NC}"
fi

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "[2/3] Checking dependencies..."

cd pips-agent

if [ -f "requirements.txt" ]; then
    echo "Installing/verifying Python dependencies..."
    pip install -r requirements.txt --quiet
    echo -e "${GREEN}Dependencies ready${NC}"
else
    echo -e "${YELLOW}requirements.txt not found${NC}"
fi

# ============================================
# VERIFY ENVIRONMENT
# ============================================

echo ""
echo "[3/3] Verifying environment..."

# Check OpenCV
if python -c "import cv2" 2>/dev/null; then
    echo -e "${GREEN}✓ OpenCV installed${NC}"
else
    echo -e "${RED}✗ OpenCV not found${NC}"
fi

# Check NumPy
if python -c "import numpy" 2>/dev/null; then
    echo -e "${GREEN}✓ NumPy installed${NC}"
else
    echo -e "${RED}✗ NumPy not found${NC}"
fi

# Check scikit-learn
if python -c "import sklearn" 2>/dev/null; then
    echo -e "${GREEN}✓ scikit-learn installed${NC}"
else
    echo -e "${RED}✗ scikit-learn not found${NC}"
fi

# Check pytest
if python -c "import pytest" 2>/dev/null; then
    echo -e "${GREEN}✓ pytest installed${NC}"
else
    echo -e "${YELLOW}⚠ pytest not found (needed for tests)${NC}"
    echo "  Install with: pip install pytest"
fi

cd ..

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Task: Implement diamond cell inference (Strategy 3)"
echo "File: pips-agent/utils/cv_extraction_v2.py"
echo ""
echo "Next steps:"
echo "  1. Implement detect_by_constraint_labels() function"
echo "  2. Integrate into multi-strategy system"
echo "  3. Add test coverage"
echo ""
echo "To run tests:"
echo "  cd pips-agent"
echo "  python test_user_puzzle_cv.py           # Existing tests"
echo "  python -m pytest test_cv_extraction_v2.py -v  # New tests (after creation)"
echo ""
echo "To test detection manually:"
echo "  cd pips-agent"
echo "  python -c \"from utils.cv_extraction_v2 import extract_puzzle_multi_strategy; result = extract_puzzle_multi_strategy('../IMG_2051.png', 'debug'); print(result)\""
echo ""
echo "========================================"
