#!/bin/bash

# Auto-Build Environment Setup - Spec 013
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting pips-solver (React Native)..."
echo "----------------------------------------"
cd pips-solver && npm run start &
PIPS_SOLVER_PID=$!
wait_for_service 3000 "pips-solver"

# ============================================
# OPTIONAL: Start cv-service if needed
# ============================================

# Uncomment if testing with AI extraction:
# echo ""
# echo "Starting cv-service (FastAPI)..."
# echo "----------------------------------------"
# cd ../cv-service && python main.py &
# CV_SERVICE_PID=$!
# wait_for_service 8080 "cv-service"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  pips-solver:  http://localhost:3000 (Metro bundler)"
echo "                Open Expo Go app and scan QR code"
echo ""
# echo "  cv-service:   http://localhost:8080 (if uncommented)"
echo ""
echo "To test the dimension editor:"
echo "  1. Open pips-solver in Expo Go"
echo "  2. Tap 'New Puzzle' or open existing draft"
echo "  3. Run AI extraction on a puzzle image"
echo "  4. In AIVerificationModal, look for Grid section"
echo "  5. Tap 'Edit Dimensions' button"
echo "  6. Test +/- controls for rows and columns"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for user interrupt
wait
