#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 014: Accurate Confidence Scoring

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec 014: Accurate Confidence Scoring"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Backend (cv-service)
echo ""
echo "Starting cv-service (FastAPI)..."
cd cv-service && python main.py &
CV_PID=$!
wait_for_service 8080 "cv-service"

# Frontend (pips-solver)
echo ""
echo "Starting pips-solver (React Native/Expo)..."
cd ../pips-solver && npm run start &
SOLVER_PID=$!
wait_for_service 3000 "pips-solver"

# Note: pips-agent is a CLI tool, started on-demand

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  cv-service:  http://localhost:8080"
echo "  cv-service docs: http://localhost:8080/docs"
echo "  pips-solver: http://localhost:3000"
echo ""
echo "PIDs:"
echo "  cv-service: $CV_PID"
echo "  pips-solver: $SOLVER_PID"
echo ""
echo "To test confidence scoring:"
echo "  curl -X POST http://localhost:8080/crop-puzzle \\"
echo "    -F 'image=@test-image.jpg' | jq '.confidence, .threshold'"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Wait for Ctrl+C
trap "echo ''; echo 'Stopping services...'; kill $CV_PID $SOLVER_PID 2>/dev/null; exit 0" INT
wait
