#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 017: Commit and Merge All Feature Branches

set -e

echo "========================================"
echo "Branch Consolidation Pre-Check"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# GIT REPOSITORY CHECKS
# ============================================

echo ""
echo "Checking Git Repository State..."
echo ""

# Check if we're in a git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
    echo -e "${RED}ERROR: Not inside a git repository${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Git repository detected${NC}"

# Show current branch
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo -e "Current branch: ${YELLOW}$CURRENT_BRANCH${NC}"

# Count local branches
BRANCH_COUNT=$(git for-each-ref --format="%(refname:short)" refs/heads/ | wc -l)
echo -e "Total local branches: ${YELLOW}$BRANCH_COUNT${NC}"

# Check for uncommitted changes on current branch
STAGED_COUNT=$(git diff --cached --stat | wc -l)
UNSTAGED_COUNT=$(git status --porcelain | wc -l)
echo -e "Staged changes: ${YELLOW}$STAGED_COUNT${NC}"
echo -e "Total pending changes: ${YELLOW}$UNSTAGED_COUNT${NC}"

# ============================================
# WORKTREE STATUS
# ============================================

echo ""
echo "Checking Worktree Status..."
echo ""

WORKTREE_COUNT=$(git worktree list | wc -l)
echo -e "Total worktrees: ${YELLOW}$WORKTREE_COUNT${NC}"

# List worktrees in .worktrees directory
if [ -d ".worktrees" ]; then
    LOCAL_WORKTREE_COUNT=$(ls -d .worktrees/*/ 2>/dev/null | wc -l)
    echo -e "Local worktrees (.worktrees/): ${YELLOW}$LOCAL_WORKTREE_COUNT${NC}"
fi

# ============================================
# BRANCH SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Branch Summary"
echo "========================================"
echo ""

echo "Auto-Claude Branches:"
git for-each-ref --format="%(refname:short)" refs/heads/ | grep "auto-claude/" | while read branch; do
    COMMITS=$(git rev-list --count main..$branch 2>/dev/null || echo "?")
    echo "  - $branch ($COMMITS commits ahead)"
done

echo ""
echo "Other Branches:"
git for-each-ref --format="%(refname:short)" refs/heads/ | grep -v "auto-claude/" | grep -v "^main$" | while read branch; do
    COMMITS=$(git rev-list --count main..$branch 2>/dev/null || echo "?")
    echo "  - $branch ($COMMITS commits ahead)"
done

# ============================================
# SAFETY CHECKS
# ============================================

echo ""
echo "========================================"
echo "Pre-Merge Safety Checklist"
echo "========================================"
echo ""

# Check for existing backup tag
if git tag -l "backup-pre-merge-*" | head -1 | grep -q "backup"; then
    echo -e "${GREEN}✓ Backup tag exists${NC}"
else
    echo -e "${YELLOW}⚠ No backup tag found - will be created${NC}"
fi

# Check main branch exists
if git show-ref --verify --quiet refs/heads/main; then
    echo -e "${GREEN}✓ Main branch exists${NC}"
else
    echo -e "${RED}✗ Main branch not found${NC}"
    exit 1
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready for Branch Consolidation"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Review branch inventory above"
echo "  2. Run: source auto-claude/.venv/bin/activate"
echo "  3. Run: python auto-claude/run.py --spec 017 --parallel 1"
echo ""
echo "Estimated operations:"
echo "  - Backup tag creation"
echo "  - ~$BRANCH_COUNT branch merges"
echo "  - Post-merge verification"
echo ""
