#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Graduated Hint System

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# CHECK ENVIRONMENT VARIABLES
# ============================================

echo ""
echo "Checking environment variables..."

if [ -z "$ANTHROPIC_API_KEY" ]; then
    echo -e "${YELLOW}Warning: ANTHROPIC_API_KEY not set${NC}"
    echo "  Set it in pips-agent/.env"
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Start pips-agent HTTP server (FastAPI)
echo -e "${YELLOW}Starting pips-agent API server...${NC}"
cd pips-agent
uvicorn api_server:app --port 8001 --reload &
PIPS_AGENT_PID=$!
cd ..
wait_for_service 8001 "pips-agent API"

# Start pips-solver frontend (Expo)
echo -e "${YELLOW}Starting pips-solver frontend...${NC}"
cd pips-solver
npm start &
PIPS_SOLVER_PID=$!
cd ..
wait_for_service 3000 "pips-solver"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  pips-agent API:  http://localhost:8001"
echo "  pips-solver:     http://localhost:3000"
echo ""
echo "API Documentation:"
echo "  http://localhost:8001/docs"
echo ""
echo "To stop services:"
echo "  kill $PIPS_AGENT_PID $PIPS_SOLVER_PID"
echo ""
