#!/bin/bash

# Auto-Claude Branch Merge - Environment Setup
# Generated by Planner Agent
# Spec: 017-merge-auto-claude-branches-into-copilot-fixes

set -e

echo "========================================"
echo "Git Branch Merge - Pre-Flight Check"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Checking git repository state..."
echo ""

# Check if we're in a git repository
if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo -e "${RED}Error: Not in a git repository${NC}"
    exit 1
fi

# Check for detached HEAD
if git symbolic-ref -q HEAD >/dev/null; then
    CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
    echo -e "${GREEN}✓ On branch: $CURRENT_BRANCH${NC}"
else
    echo -e "${RED}✗ Detached HEAD state detected${NC}"
    echo "Please checkout a branch before proceeding"
    exit 1
fi

# Count auto-claude branches
BRANCH_COUNT=$(git branch --list 'auto-claude*' | wc -l)
echo -e "${GREEN}✓ Found $BRANCH_COUNT auto-claude branches${NC}"

# Check if copilot-fixes exists
if git show-ref --verify --quiet refs/heads/copilot-fixes; then
    echo -e "${GREEN}✓ copilot-fixes branch exists${NC}"
else
    echo -e "${YELLOW}⚠ copilot-fixes branch does not exist (will be created)${NC}"
fi

# Check for uncommitted changes
if ! git diff-index --quiet HEAD --; then
    echo -e "${YELLOW}⚠ Uncommitted changes detected${NC}"
    echo "These will need to be handled before merging"
else
    echo -e "${GREEN}✓ Working directory is clean${NC}"
fi

# ============================================
# BRANCH LIST
# ============================================

echo ""
echo "Auto-claude branches to merge:"
echo "----------------------------------------"
git branch --list 'auto-claude*' | sed 's/^[ *]*/  /'
echo "----------------------------------------"
echo ""

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Pre-Flight Check Complete!"
echo "========================================"
echo ""
echo "Ready to begin merge operation:"
echo "  - Current branch: $CURRENT_BRANCH"
echo "  - Branches to merge: $BRANCH_COUNT"
echo "  - Target branch: copilot-fixes"
echo ""
echo "The implementation agent will:"
echo "  1. Create backup tag (pre-merge-backup)"
echo "  2. Commit any uncommitted changes on each branch"
echo "  3. Merge all auto-claude branches into copilot-fixes"
echo "  4. Verify merge integrity"
echo ""
echo "NOTE: This is a git operation script."
echo "No development services need to be started."
echo ""
