#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 010

set -e

echo "========================================"
echo "Enhanced OCR Constraint Detection Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# VERIFY TESSERACT INSTALLATION
# ============================================

echo ""
echo "Step 1: Verifying Tesseract OCR binary installation..."
if command -v tesseract &> /dev/null; then
    tesseract_version=$(tesseract --version 2>&1 | head -n 1)
    echo -e "${GREEN}✓ Tesseract found: $tesseract_version${NC}"
else
    echo -e "${RED}✗ Tesseract binary not found${NC}"
    echo ""
    echo "Tesseract must be installed separately. Install it using:"
    echo "  - Ubuntu/Debian: sudo apt-get install tesseract-ocr"
    echo "  - macOS: brew install tesseract"
    echo "  - Windows: Download from https://github.com/UB-Mannheim/tesseract/wiki"
    exit 1
fi

# ============================================
# SETUP PIPS-AGENT SERVICE
# ============================================

echo ""
echo "Step 2: Setting up pips-agent service..."

# Create virtual environment if it doesn't exist
if [ ! -d "pips-agent/venv" ]; then
    echo "Creating Python virtual environment..."
    cd pips-agent
    python -m venv venv
    cd ..
    echo -e "${GREEN}✓ Virtual environment created${NC}"
else
    echo -e "${YELLOW}Virtual environment already exists${NC}"
fi

# Activate and install dependencies
echo "Installing Python dependencies..."
cd pips-agent
source venv/bin/activate 2>/dev/null || . venv/Scripts/activate 2>/dev/null

pip install -q --upgrade pip
pip install -q -r requirements.txt

echo -e "${GREEN}✓ Dependencies installed${NC}"

# Verify critical packages
echo "Verifying OCR dependencies..."
python -c "import pytesseract; import cv2; import numpy; print('✓ All OCR dependencies available')" || {
    echo -e "${RED}✗ Failed to import OCR dependencies${NC}"
    exit 1
}

cd ..

# ============================================
# SETUP DEBUG OUTPUT DIRECTORY
# ============================================

echo ""
echo "Step 3: Creating debug output directory..."
mkdir -p pips-agent/debug_ocr
echo -e "${GREEN}✓ Debug directory created: pips-agent/debug_ocr${NC}"

# ============================================
# ENVIRONMENT VARIABLES CHECK
# ============================================

echo ""
echo "Step 4: Checking environment variables..."

if [ -f "pips-agent/.env" ]; then
    echo -e "${GREEN}✓ .env file exists${NC}"

    if grep -q "DEBUG_OUTPUT_DIR" pips-agent/.env; then
        echo -e "${GREEN}✓ DEBUG_OUTPUT_DIR configured${NC}"
    else
        echo -e "${YELLOW}⚠ DEBUG_OUTPUT_DIR not found in .env${NC}"
        echo "  Recommended: Add 'DEBUG_OUTPUT_DIR=./debug_ocr' to pips-agent/.env"
    fi

    if grep -q "ANTHROPIC_API_KEY" pips-agent/.env; then
        echo -e "${GREEN}✓ ANTHROPIC_API_KEY configured${NC}"
    else
        echo -e "${YELLOW}⚠ ANTHROPIC_API_KEY not found in .env${NC}"
    fi
else
    echo -e "${YELLOW}⚠ No .env file found${NC}"
    echo "  Copy pips-agent/.env.example to pips-agent/.env and configure variables"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo -e "${GREEN}✓ Tesseract OCR binary verified${NC}"
echo -e "${GREEN}✓ Python dependencies installed${NC}"
echo -e "${GREEN}✓ Debug output directory created${NC}"
echo ""
echo "Services:"
echo "  pips-agent: Python utilities service (no server)"
echo ""
echo "To activate Python environment:"
echo "  cd pips-agent && source venv/bin/activate"
echo ""
echo "To test OCR functionality:"
echo "  cd pips-agent && python test_user_puzzle_cv.py"
echo ""
echo "To run the agent:"
echo "  cd pips-agent && python main.py"
echo ""
echo -e "${YELLOW}Next: Run the coder agent to implement the OCR enhancements${NC}"
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 010 --parallel 1"
echo ""
